### PR TITLE
Create logistic_regression.py

### PR DESCRIPTION
**Pull request by stktyagi**

### CODE REVIEW

**Comment by karsterr** [comment]
@stktyagi  my grandmother was in critical health last week. She passed away two days ago. I apologize for the wait. I appreciate your patience.

**Comment by stktyagi** [comment]
I hope your grandmother rests in peace. I totally understand the delay and hope you recover from your loss.

**Comment by karsterr** [comment]
@stktyagi Greetings, I want you to inform that I'm back. I got tough weeks but I get over it. I really appreciate your support and patience. Much thanks.

This is a repository I have created and maintained for learning. I would be grateful if you could briefly explain the code you wrote.

**Comment by stktyagi** [comment]
It reads a CSV file into a Pandas DataFrame, drops unnecessary columns ('timestamp'), and converts salary ranges and employee counts into numeric values.
Categorical variables are one-hot encoded, and a binary target variable ('salary_binary') is created based on whether each salary is above the median salary in the dataset.
After preprocessing, the data is split into training and testing sets (80% training, 20% testing) using train_test_split.
A logistic regression model is trained on the training data (X_train and y_train) to predict the binary salary classification.
Finally, the model's accuracy is evaluated on the test data (X_test and y_test), and the accuracy score is printed.

**Comment by karsterr** [comment]
I got it. Thanks again for your efforts. Have a nice day.

**Pull request merged**
